### ISSUE TITLE
Rebuilding CSteamworks.dll

### ISSUE THREAD

**Issue by oturaz** [rlabrecque/CSteamworks#10]
I tried to update the dll/dylib/so files with the latest steam API. I put everything as required in the instructions in the root, afterwards I put the parser files in the parser, ran the CSteamworks2.py and after the .cpp files were generated, at the last step when I have to build them into dylib (I only have osx at work) I get the following error: "CSteamworks.bundle doesn't have any SDKs to build for My Mac. You can change CSteamworks.bundle's Base SDK or Supported Platforms to support My Mac.". No idea what this is, but there is no CSteamworks.bundle in any of the folders. I tried to take one from a functioning postcompiled one and moved it in every folder to no avail. If someone could tell me what I'm doing wrong or just send me all the updated dlls/dylibs/sos, I would be very grateful.

**Comment by rlabrecque** [comment]
Hey @oturaz, CSteamworks is a little tricky to build on OSX because we build for OSX 10.6 or 10.7... which requires a very old version of OSX and XCode.

You can probably build with a newer version of the OSX SDK by fiddling with the project settings but CSteamworks.dll is already built for the latest version of the Steamworks SDK (1.37)! You can find it on the [Releases](https://github.com/rlabrecque/CSteamworks/releases/tag/v1.27-1.37) page or in Steamworks.NET master on github.

**Comment by oturaz** [comment]
Well, told boss I give up with the steam controller. I tried to update the code to work with the new controller functions, but none seems to work. When I use GetConnectedControllers for example, Unity just crashes. At this point I can't really ask you for any more help since you already helped me so much. I would feel like a complete loser if I did. I will however post my attempt at updating one of the functions. I would greatly appreciate your opinion on what I tried, but please look over it only if you are bored and have nothing better to do.

**In NativeMethids.cs**
`[DllImport(NativeLibraryName, CallingConvention = CallingConvention.Cdecl)]
		[return: MarshalAs(UnmanagedType.I1)]
		public static extern int ISteamController_GetConnectedControllers (out uint controllerHandle);`
**In isteamcontroller.cs**
`public static int GetConnectedControllers(out uint handlesOut) {
			InteropHelp.TestIfAvailableClient ();
			return NativeMethods.ISteamController_GetConnectedControllers(out handlesOut);
		}`
**And I just call it like this**
`               SteamController.Init ();
		public uint controllerOut;
		SteamController.GetConnectedControllers(out controllerOut);
		SteamController.Shutdown ();`

**Comment by rlabrecque** [comment]
Err, you shouldn't really be modifing any of the files in Plugins/Steamworks.NET/ yourself, did you overwrite **everything** in there with the latest version from master on github?

**Comment by oturaz** [comment]
Just the controller ones. I guess i could write a script that generates files in order to update them all, but something tells me it would still not work and that i would be wasting time. U think itd be worth a shit? Other than changing The plugin functions i see nothing that could be changed. Was my reasoning wrong?

**Comment by rlabrecque** [comment]
No, everything has to be updated together, all  he .cs and .dll/so/bundle files need to stay in sync with eachother. You shouldn't need a script or anything to update everything, Just open your Assets folder in Explorer (on Windows) or Finder (on OSX) and overwrite the Editor/ and Plugins/ folder with the Editor/ and Plugins/ folders from https://github.com/rlabrecque/Steamworks.NET/archive/master.zip

**Comment by oturaz** [comment]
I'm so blind...can't believe I didn't see there was an updated version...I apologize I wasted so much of your time with my stupidity. Unfortunately even with those unity still crashes when I try to use the GetConnectedControllers
