### ISSUE TITLE
How to link/include?

### ISSUE THREAD

**Issue by charliesgames** [rlabrecque/CSteamworks#11]
Is it just a case of loading the dll and registering the functions? or is there a C header file i should be including along with linking the lib? This is for a C program building with minGW gcc.

Sorry if this is a bit noobish.

Cheers
Charlie

**Comment by charliesgames** [comment]
i should add that i'm currently using windows, though i intend to use this with macs and linux later on.

**Comment by rlabrecque** [comment]
Hey charliesgames, I'm not sure of anyone actually using it from C! I'm also not sure how good the support with MinGW will be. The releases don't ship with a .lib file to link with, but I could get you one of those if using one created with MSVC2010 (with the visual studio runtimes statically linked) works with MinGW.

**Comment by charliesgames** [comment]
Hi, it's no problem if it means more work for you. I do have a wrapper of some of the steamworks stuff anyway, i just wondered if this more complete on would be easy to add in as a superior replacement.

I did get some basic functionality out of loading the library from the dll, though i think given the timeframe i'm working with i'm better off leaving this for now and taking a better look later. If i come up with something i'll let you know.

Thanks for answering my question,

Cheers
Charlie.

**Comment by rlabrecque** [comment]
Sounds good. Hopefully with time the official C API wrapper will actually support C too.

Both Steamworks.NET and the official C API both suffer from the fact that they they were really just designed to be used with other languages through FFI, so not much thought was given into C usage unfortunately. Especially given how much stuff is moving towards C++ including GCC itself a few years ago.

I'm going to keep this open until there's an easy solution though.

**Comment by EvilPudding** [comment]
Hi, I am developing a C game-engine, and I would like to have steam as a module for it's ingame interface and lobbying. This thread is leaving me a bit confused...

@rlabrecque what do you mean by "the official C API"? What are the problems in using this in plain C?

**Comment by EvilPudding** [comment]
The difference between using this through FFI or the plain way is just creating a proper C header then letting the linker find the functions. This seems really easy to do since you already loop through all the functions, is there a caveat I'm missing?

**Comment by EvilPudding** [comment]
The difference between using this through FFI or the plain way is just creating a proper C header then letting the linker find the functions. This seems really easy to do since you already loop through all the functions, is there a caveat I'm missing?

**Comment by EvilPudding** [comment]
Thank you for the reply, which header are you talking about? `steam_api.h`? I've spent the entire day going through the `steam_api.json` and generating equivalent C code, is this a waste of time? Thanks again for the info.

**Comment by EvilPudding** [comment]
Also, do I need to create any wrapper cpp code if I do this or is that not necessary anymore?

**Comment by rlabrecque** [comment]
It's called "steam_api_flat.h" from the latest Steamworks SDK, to get it working with C you mostly just have to replace any C++ specific stuff, Change `CSteamID`/`CGameID` to `uint64_t` etc.
Then no you don't need any cpp stuff, just link steam_api[64].lib and use that header.

steam_api.json is how they generated steam_api_flat.h

**Comment by EvilPudding** [comment]
I did mostly what you said, but I had to generate all the enums and structures from the `steam_api.json`, it's also missing the `SteamAPI_Init` and all of the functions from `steam_api.h`. It seems to be working so far, I've fetched the avatar and nickname, though I haven't managed to make the Overlay work. Also, I had to copy all of the version string defines from each file, and I don't know if it's feasible to keep this updated without auto-generation, since the C++ version get's the version strings from inline methods which don't when linking with C.

**Comment by EvilPudding** [comment]
Thanks for the info, your repo was the first thing that came up when searching for this, and I had no idea in which direction to go. Thanks for all the pointers.

**Comment by rlabrecque** [comment]
I actually forgot one important bit, Callbacks/CallResults. I'm not sure what you'll have to do about those, but you may need to implement your own system to deal with them unfortunately.

**Comment by EvilPudding** [comment]
I noticed those were missing and just added a `TODO` until I notice where they're needed.
By the way, how legal do you think it is to have a repo with the header I generated today?

**Comment by rlabrecque** [comment]
I wouldn't worry about it legally, I was given the thumbs up multiple times from Valve to even host the raw SDK.

**Comment by EvilPudding** [comment]
That eases my mind, thanks!
