### ISSUE TITLE
Function Declarations in a header

### ISSUE THREAD

**Issue by rlabrecque** [rlabrecque/CSteamworks#2]
We really should be including the wrapper function declarations in a header so that people can use the generated files with their application directly.

This wont get done until someone requests it though.

This would in theory allow the Steam API to be used directly from C without any C++.

**Comment by CapsAdmin** [comment]
I'm interested in using this with LuaJIT. I tried to make a header automatically from the C++ files but there were too many issues with the declarations not being standard C and other inconsistencies so I ended up doing the rest manually. 

I'd force a standard naming scheme so it would be easier to parse the header to generate a wrapper but it might be difficult to do manually.

**Comment by rlabrecque** [comment]
That's a pretty valid point that I haven't actually thought of!

But have you looked into Valve's Flat C API and their json stuff that shipped in 1.32 yet? CSteamworks should be rather obsolete because of it.

**Comment by CapsAdmin** [comment]
Oh that seems useful. Thanks for the heads up!
